version: '3.9'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ../backend
    command: sh -c "python main.py"
    volumes:
      - ../backend:/tmp/backend
    ports:
      - "8000:8000"
    env_file:
      - .env