"""Database creation

Revision ID: ab822e03a0cd
Revises: 9281a28b4d07
Create Date: 2023-11-01 00:05:10.271144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab822e03a0cd'
down_revision: Union[str, None] = '9281a28b4d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Никнейм', sa.String(), nullable=True),
    sa.Column('Эл. почта', sa.String(), nullable=True),
    sa.Column('пароль', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Баланс', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Никнейм'),
    sa.UniqueConstraint('Эл. почта')
    )
    op.create_index(op.f('ix_users_ID'), 'users', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ID'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
